### ISSUE TITLE
unable to find module error

### ISSUE THREAD

**Issue by siemya** [siwymilek/react-native-camera-library#1]
`import CameraLibrary from "react-native-camera-library"`

i linked the module with rnpm, and imported as above. but weirdly i get a `unable to find module` error.

**Comment by siwymilek** [comment]
I not sure how rnpm works. You need to check manually whether the is linked to your project. Your target -> built phrases -> Link Binary With Libraries. Make sure libCameraLibrary.a is added.

**Comment by siemya** [comment]
i checked it manually by following the manual linking steps, it is linked as expected...

**Comment by siwymilek** [comment]
@siemya: I released hot-fix. Try now to use it.
